version: '3.8'

services:

  # --- SERVICE 1 : LA BASE DE DONNÉES POSTGRESQL ---
  db:
    image: postgres:15-alpine
    container_name: ast_ai_postgres
    restart: always
    environment:
      POSTGRES_DB: ast_ai
      POSTGRES_USER: ast_ai_user
      POSTGRES_PASSWORD: ast_ai_password_secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


# --- SERVICE 2 : LE SERVEUR LLM LOCAL (Ollama) ---
  ollama:
    image: ollama/ollama:latest
    container_name: ast_ai_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ast_ai_network

  # --- SERVICE 3 : CONTENEUR D'INITIALISATION OLLAMA ---
  ollama-init:
    image: ollama/ollama:latest
    container_name: ast_ai_ollama_init
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: [ "ollama", "pull", "${OLLAMA_MODEL}" ]
    environment:
      - OLLAMA_HOST=ollama
    depends_on:
      - ollama
    networks:
      - ast_ai_network

volumes:
  postgres_data:
  ollama_data:

networks:
  ast_ai_network:
    driver: bridge
